global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['jmx-exporter:8080']
    scrape_interval: 30s
