version: '3.8'

networks:
  kafka-existing:
    external:
      name: kafkablockchainoptimization_kafka-net

volumes:
  orderer-data:
  peer0-org1-data:

services:
  # Orderer senza dependency su kafka (usa solo rete)
  orderer:
    image: hyperledger/fabric-orderer:2.4.7
    container_name: orderer
    hostname: orderer.example.com
    networks:
      - kafka-existing
    ports:
      - "7050:7050"
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      
      # Kafka Integration (connessione diretta via rete)
      - ORDERER_KAFKA_BROKERS=[kafka:29092]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      
      # Timeouts per stabilità
      - ORDERER_GENERAL_KEEPALIVE_SERVERMININTERVAL=60s
      - ORDERER_GENERAL_KEEPALIVE_SERVERTIMEOUT=20s
      
      # Batch settings ottimizzati
      - ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT=10
      - ORDERER_GENERAL_BATCHSIZE_ABSOLUTEMAXBYTES=1048576
      - ORDERER_GENERAL_BATCHSIZE_PREFERREDMAXBYTES=524288
      - ORDERER_GENERAL_BATCHTIMEOUT=2s
      
    volumes:
      - ./blockchain-config/genesis.block:/var/hyperledger/orderer/genesis.block:ro
      - ./blockchain-config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp:ro
      - orderer-data:/var/hyperledger/production/orderer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -lnp | grep :7050 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Peer semplificato
  peer0-org1:
    image: hyperledger/fabric-peer:2.4.7
    container_name: peer0-org1
    hostname: peer0.org1.example.com
    networks:
      - kafka-existing
    ports:
      - "7051:7051"
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=kafkablockchainoptimization_kafka-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      
      # Semplificazioni per testing
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=false
      
    volumes:
      - /var/run/:/host/var/run/
      - ./blockchain-config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp:ro
      - peer0-org1-data:/var/hyperledger/production
    restart: unless-stopped

  # CLI semplificato
  cli:
    image: hyperledger/fabric-tools:2.4.7
    container_name: cli
    hostname: cli
    networks:
      - kafka-existing
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      
      # Path semplificati
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 3600'
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincodes:/opt/gopath/src/github.com/chaincode:ro
      - ./blockchain-config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/:ro
    restart: unless-stopped
