version: '3.8'

networks:
  kafka-net:
    driver: bridge

volumes:
  kafka-data:
  zk-data:
  prometheus-data:
  grafana-data:

services:
  # Zookeeper (single node for starting simple)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zk-data:/var/lib/zookeeper/data
    restart: unless-stopped

  # Kafka broker (single node initially)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
      # Producer configs (these need different names)
      KAFKA_PRODUCER_BATCH_SIZE: 16384
      KAFKA_PRODUCER_LINGER_MS: 0
      KAFKA_PRODUCER_COMPRESSION_TYPE: none
      KAFKA_PRODUCER_BUFFER_MEMORY: 33554432
      
      # Server configs
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 8
      
      # Blockchain requirements
      KAFKA_PRODUCER_ACKS: all
      KAFKA_PRODUCER_RETRIES: 2147483647
      KAFKA_PRODUCER_ENABLE_IDEMPOTENCE: 'true'
      KAFKA_PRODUCER_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: 1
      
      # Monitoring
      KAFKA_JMX_PORT: 9094
      KAFKA_JMX_HOSTNAME: kafka
      
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./configs:/configs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v2.45.0
    hostname: prometheus
    container_name: prometheus
    networks:
      - kafka-net
    ports:
      - "9090:9090"
    volumes:
      - ./configs/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.0.0
    hostname: grafana
    container_name: grafana
    networks:
      - kafka-net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  # JMX Exporter for Kafka metrics
  jmx-exporter:
    image: sscaling/jmx-prometheus-exporter:latest
    hostname: jmx-exporter
    container_name: jmx-exporter
    networks:
      - kafka-net
    ports:
      - "8080:8080"
    environment:
      - CONFIG_YML=/etc/jmx_exporter/config.yml
    volumes:
      - ./configs/monitoring/jmx_exporter_config.yml:/etc/jmx_exporter/config.yml:ro
    depends_on:
      - kafka
    restart: unless-stopped

  # Test runner container
  test-runner:
    build:
      context: .
      dockerfile: docker/base/Dockerfile.test
    hostname: test-runner
    container_name: test-runner
    networks:
      - kafka-net
    volumes:
      - ./scripts:/scripts
      - ./configs:/configs  
      - ./results:/results
      - ./src:/src
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
    command: ["sleep", "infinity"]
    restart: unless-stopped