global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9999']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'fabric-orderer'
    static_configs:
      - targets: ['orderer:8443']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'fabric-peers'
    static_configs:
      - targets: ['peer0-org1:9444', 'peer0-org2:9445']
    scrape_interval: 15s
    metrics_path: /metrics
