global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX Metrics via JMX Exporter
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['jmx-exporter:5556']
    scrape_interval: 10s
    metrics_path: /metrics

  # System metrics (if needed)
  - job_name: 'kafka-container'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 15s
    metrics_path: /metrics