hostPort: kafka:9999
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false

rules:
  # Kafka Producer Metrics
  - pattern: kafka.producer<type=producer-metrics, client-id=(.*)><>(.+)
    name: kafka_producer_$2
    labels:
      client_id: "$1"
    help: "Kafka producer metrics"
    type: GAUGE

  # Kafka Server Metrics
  - pattern: kafka.server<type=(.+), name=(.+)><>Value
    name: kafka_server_$1_$2
    help: "Kafka server metrics"
    type: GAUGE

  # Kafka Network Metrics
  - pattern: kafka.network<type=(.+), name=(.+), request=(.*)><>(.+)
    name: kafka_network_$1_$2_$4
    labels:
      request: "$3"
    help: "Kafka network metrics"
    type: GAUGE

  # Kafka Log Metrics
  - pattern: kafka.log<type=(.+), name=(.+), topic=(.+), partition=(.*)><>Value
    name: kafka_log_$1_$2
    labels:
      topic: "$3"
      partition: "$4"
    help: "Kafka log metrics"
    type: GAUGE

  # JVM Metrics
  - pattern: java.lang<type=Memory><HeapMemoryUsage>(.+)
    name: jvm_memory_heap_$1
    help: "JVM heap memory usage"
    type: GAUGE

  - pattern: java.lang<type=Memory><NonHeapMemoryUsage>(.+)
    name: jvm_memory_nonheap_$1
    help: "JVM non-heap memory usage"
    type: GAUGE

  - pattern: java.lang<type=GarbageCollector, name=(.+)><>CollectionCount
    name: jvm_gc_collection_count
    labels:
      gc: "$1"
    help: "JVM GC collection count"
    type: COUNTER

  - pattern: java.lang<type=GarbageCollector, name=(.+)><>CollectionTime
    name: jvm_gc_collection_time_ms
    labels:
      gc: "$1"
    help: "JVM GC collection time"
    type: COUNTER